nodeId: '123'
serviceName: testServers
host: 0.0.0.0
hostname: test
port: 8888
rpcPort: 8889
mysql:
  edu:
    username: root
    password: '123456'
    host: 127.0.0.1
    port: 3306
    database: oa_settle
redis:
  hosts:
    - 127.0.01:6379
  db: 0
  host: 127.0.01
  password: ''
  port: 6379
nats:
  host: 127.0.01
  username: ''
  password: ''
  port: 4222
etcd:
  hosts:
    - 127.0.0.1:2379
  username: ''
  password: ''
